# ASPECTS
aspect.agent59_agentBase=Informations de base pour un agent du département du Nord
aspect.agent59_agentIdentite=Informations sur l'identité de l'agent

# PROPRIETES
prop.agent59_matriculeAgent=Matricule

prop.agent59_nomAgent=Nom
prop.agent59_prenomAgent=Prénom
prop.agent59_dateNaissanceAgent=Date de naissance


