# ASPECTS
# ASPECTS
aspect.pleiades59_donneesPleiades=Les données issues de pléiades
aspect.pleiades59_donneeTypee=Une donnée typée issue de pléiades
aspect.pleiades59_codeGroupementPleiades=Le code de groupement pleiades
aspect.pleiades59_codeFamillePleiades=Le code de famille pleiades
aspect.pleiades59_codeTypeDocumentPleiades=Le code du type de document pleiades

# PROPRIETES
prop.pleiades59_nomenclaturePleiades=Le type de document nomenclature
prop.pleiades59_codePleiades=Code
prop.pleiades59_libellePleiades=Libellé


